name: Lint (type checking, security, code quality, ruff)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.13
          pip-version: 24

      - name: Linting
        run: |
          pip install pre-commit interrogate
          pre-commit run --all-files -v --show-diff-on-failure
